import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Check, Layers, Sparkles, ChevronDown, Plus, CornerDownRight } from 'lucide-react';
import { Flower, Switch } from './components';
function TreeRow({ tree, asked, onToggle }) {
  const [expanded, setExpanded] = useState(false);
  return <div className={`tree-row ${expanded ? 'expanded' : ''}`}><button className="tree-summary" aria-expanded={expanded} aria-controls={`details-${tree.id}`} onClick={() => setExpanded(!expanded)}><div className="tree-symbol"><Layers size={19}/></div><div><h3>{tree.question}</h3><p>{asked ? `${asked} in your inbox · ` : ''}used {tree.usedCount} times</p></div><ChevronDown size={17} className={expanded ? 'rotated' : ''}/></button><div className="tree-status-line"><span className={tree.autoSend ? 'auto-badge' : 'review-badge'}>{tree.autoSend ? <Sparkles size={11}/> : <Check size={11}/>} {tree.autoSend ? 'sends itself' : 'you approve'}</span><Switch checked={tree.autoSend} onChange={() => onToggle(tree)} label={`Auto-send: ${tree.question}`}/></div><AnimatePresence>{expanded && <motion.div id={`details-${tree.id}`} className="tree-details" initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}><div className="answer-fork">{tree.contextQuestion ? <><div className="fork-question">“{tree.contextQuestion}”</div>{tree.branches.map(branch => <div className="fork-branch" key={branch.condition}><CornerDownRight size={16}/><div><strong>{branch.condition}</strong><p>{branch.answer}</p></div></div>)}</> : <p>{tree.flatAnswer || tree.branches[0]?.answer}</p>}</div><div className="receipts"><span className="eyebrow">{tree.builtFrom?.length ? `BUILT FROM ${tree.builtFrom.length} OF MAYA’S PAST REPLIES` : 'SAVED BY YOU. IN YOUR OWN WORDS.'}</span>{tree.builtFrom?.slice(0, 2).map((excerpt, i) => <blockquote key={i}>“{excerpt}”</blockquote>)}</div></motion.div>}</AnimatePresence></div>;
}
export default function AnswerBank({ inbox, onBuild }) {
  const { trees, stats, unansweredThemes } = inbox.bank;
  return <section className="bank-view"><div className="view-heading bank-heading"><span className="eyebrow">A LITTLE OF YOU, SAVED FOR LATER</span><h1>say it once.<br/><em>make it count.</em></h1><Flower/></div>{stats && <div className="bank-stats"><div><strong>{stats.coveragePct}<small>%</small></strong><span>covered</span></div><div><strong><s>{stats.hoursBefore}</s><ArrowRight size={14}/>{stats.hoursAfter}<small>h</small></strong><span>per month</span></div><div><strong>{stats.savedAnswers}</strong><span>saved answers</span></div></div>}<div className="section-label bank-section-label"><h2>your answer bank <span>{trees.length}</span></h2><button aria-label="Build a new saved answer" onClick={() => onBuild('')}><Plus size={19}/></button></div><div className="tree-list">{trees.length ? trees.map(tree => <TreeRow key={tree.id} tree={tree} asked={inbox.messages.filter(message => message.matchedTreeId === tree.id).length} onToggle={inbox.toggleAuto}/>) : <div className="bank-empty"><Layers size={28}/><h2>your voice belongs here.</h2><p>save your first answer. let it do a little more.</p><button className="text-button" onClick={() => onBuild('')}>build an answer <Plus size={16}/></button></div>}</div>{!!unansweredThemes?.length && <div className="themes-panel"><span className="eyebrow">YOUR NEXT “YOU ASKED…”</span><h2>{unansweredThemes.length} things they<br/>keep asking.</h2><p className="themes-intro">no saved answer yet. maybe your next post?</p>{unansweredThemes.map(theme => <div className="theme-row" key={theme.label}><div><h3>{theme.label}</h3><span>asked {theme.count} times</span></div><button onClick={() => onBuild(theme.label)} aria-label={`Build answer: ${theme.label}`}>build <ArrowUpRight size={16}/></button></div>)}<Flower/></div>}</section>;
}
